### PR TITLE
KAA-1418 [Objective-C] Change XCode project structure to use Podspec file

### PR DESCRIPTION
**Pull request by vilimets**
@abohomol Please review

### CODE REVIEW

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by abohomol** [comment]
Can you please squash all commits together? It's much easier to review all changes together rather that track specific changes from commit to commit.

**Comment by abohomol** [comment]
LGTM

**Comment by hamsternik** [comment]
@rasendubi please, merge this PR.

**Pull request merged**
