### PR TITLE
KAA-1402 [Objective-C] Endpoint access token is not sent to Kaa cluster

### PR DESCRIPTION
**Pull request by vilimets**
@abohomol please review

### CODE REVIEW

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by Oldnickus** [comment]
@kaa-leeroy add to whitelist

**Review by hamsternik — APPROVED** [review]
LGTM

**Review by abohomol — APPROVED** [review]
Looks good to me

**Comment by rasendubi** [comment]
@kaa-leeroy retest this please

**Comment by rasendubi** [comment]
@kaa-leeroy retest this please

**Comment by vadimol** [comment]
@kaa-leeroy retest this please

**Pull request merged**
