### PR TITLE
KAA-1369 Fix nix-shell for Darwin

### PR DESCRIPTION
**Pull request by rasendubi**
cc @forGGe @vnerozin

### CODE REVIEW

**Comment by vasner** [comment]
@rasendubi can you, please, provide some instructions how to test these changes?

**Comment by rasendubi** [comment]
The simplest way to see cmocka builds is to execute next command:

```
nix-build nix/ -A cmocka
```

Note that `nix-shell` doesn't work yet. I will try to get (almost) full Nix environment working on Mac OS X shortly

**Comment by rasendubi** [comment]
Pushed the rest of the patches.

To test, go to `client/client-multi/client-c` and execute:

```
nix-shell --arg cc3200Support false --arg raspberrypiSupport false --arg withValgrind false
make
```

esp8266 build fails but that's not related to Nix. (Will open a bug against Kaa shortly.)

(Note that I've already tested this on Mac OS X)

**Comment by vasner** [comment]
@rasendubi 

**nix-build nix/ -A cmocka** 
Works well.

**nix-shell --arg cc3200Support false --arg raspberrypiSupport false --arg withValgrind false**
This commands is finished with error:
**error:** Package ‘valgrind-3.11.0’ in ‘/nix/store/m9v46jannv31jh60gnbrpv20nb6g9hhi-nixpkgs/nixpkgs/pkgs/development/tools/analysis/valgrind/default.nix:58’ is not supported on ‘x86_64-darwin’, refusing to evaluate.
a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

**Comment by rasendubi** [comment]
@vnerozin are you sure, you have checked out the branch? What's output of `git log -2`?

**Comment by vasner** [comment]
git log -2
commit 406f55c829e76d244307ae2da445f8b0961579ce
Author: Alexey Shmalko rasen.dubi@gmail.com
Date:   Thu Sep 8 23:59:49 2016 +0300

```
KAA-1369 Use cmake-3.x on Darwin
```

commit 4f9d8ad108b43c124f5ac5fe6b8bf4f52a11f8b6
Author: Alexey Shmalko rasen.dubi@gmail.com
Date:   Thu Sep 8 23:46:39 2016 +0300

```
KAA-1369 Use proper patchFlags for astyle
```

**Comment by rasendubi** [comment]
Oh, reproduced locally. Will fix soon

**Comment by rasendubi** [comment]
@vnerozin I've pushed a fix. Also fixed esp8266 build on OS X.

**Comment by vasner** [comment]
Works well.

**Review by forGGe — APPROVED** [review]
Looks good

**Pull request merged**
