### PR TITLE
KAA-1301: Database configuration - reviewed.

### PR DESCRIPTION
**Pull request by hunch7**
Done as per https://github.com/kaaproject/kaa/pull/1358

### CODE REVIEW

**Comment by Oldnickus** [comment]
@kaa-leeroy test this please

**Comment by Oldnickus** [comment]
@kaa-leeroy test this please

**Comment by kaa-leeroy** [comment]
Test robot

**Comment by Oldnickus** [comment]
@kaa-leeroy test this please

**Comment by Oldnickus** [comment]
@kaa-leeroy test this please

**Comment by Oldnickus** [comment]
@kaa-leeroy test this please

**Comment by Oldnickus** [comment]
@kaa-leeroy test this please

**Comment by Oldnickus** [comment]
retest this please

**Comment by Oldnickus** [comment]
retest this please

**Comment by Oldnickus** [comment]
retest this please

**Comment by Oldnickus** [comment]
retest this please

**Review by vadimol — APPROVED** [review]

**Pull request merged**
