### PR TITLE
KAA-1157 Add redirect and update test-gh-pages.sh

### PR DESCRIPTION
**Pull request by balldir**

### CODE REVIEW

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by rasendubi** [comment]
The patch reverts parts of https://github.com/kaaproject/kaa/pull/779

**Comment by Oldnickus** [comment]
@kaa-leeroy 
add to whitelist

**Comment by rasendubi** [comment]
LGTM

**Comment by rasendubi** [comment]
Can this be merged without #793?

**Pull request merged**
