### PR TITLE
KAA-1534: updated pom release version to 0.10.0

### PR DESCRIPTION
**Pull request by agulenko**
Updated pom release version to 0.10.0

### CODE REVIEW

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by akokhanovskyi** [comment]
@kaa-leeroy add to whitelist

**Comment by rasendubi** [comment]
@kaa-leeroy add to whitelist

**Comment by akokhanovskyi** [comment]
@vtkhir @sergio-dev please help review

**Review by garniy — APPROVED** [review]

**Review by vtkhir — APPROVED** [review]

**Pull request merged**
