### PR TITLE
KAA-1018 Update copyrights to default comment syntax

### PR DESCRIPTION
**Pull request by rasendubi**

### CODE REVIEW

**Comment by iuriigolovach** [comment]
Can one of the admins verify this patch?

**Comment by rasendubi** [comment]
Middle commit is the only one worth reviewing: https://github.com/kaaproject/kaa/pull/624/commits/50f101d33d5d78618c82f4113c14a9ed1bc22324

**Comment by forGGe** [comment]
+

**Comment by abohomol** [comment]
+

**Comment by rasendubi** [comment]
retest this please

**Pull request merged**
