### PR TITLE
APP-73 Set cmake_minimum_required to higher version

### PR DESCRIPTION
**Pull request by Dubland**
/cc @rasendubi @forGGe

### CODE REVIEW

**Comment by rasendubi** [comment]
Have you tested with cmake-2.8.12?

**Comment by Dubland** [comment]
Was tested with cmake-2.8.12 and successful compiled.

**Comment by Dubland** [comment]
In this pull request https://github.com/kaaproject/kaa/pull/813 resolved for C++ SDK.

**Comment by RostakaGmfun** [comment]
@Dubland, the #813 seems to bump CMake version for C++ SDK, but does not do that for C SDK. This PR should be reopened.

**Pull request closed without merging**
