### PR TITLE
KAA-1521: Only scroll TOC in the documentation sidebar

### PR DESCRIPTION
**Pull request by Faradey27**

### CODE REVIEW

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by rasendubi** [comment]
@kaa-leeroy add to whitelist

**Comment by Faradey27** [comment]
moved this to release-0.10

**Comment by rasendubi** [comment]
@Faradey27 GitHub allows changing PR's branch if you click "Edit". No need to close

**Pull request closed without merging**
