### PR TITLE
KAA-994: Use gcc instead of ld for linking cross-compiled binaries

### PR DESCRIPTION
**Pull request by RostakaGmfun**
/cc @rasendubi

### CODE REVIEW

**Comment by rasendubi** [comment]
Looks OK, but won't merge until all sample apps are tested.

**Comment by rasendubi** [comment]
@kaa-leeroy retest this please

**Comment by RostakaGmfun** [comment]
Verified, please re-review
/cc @rasendubi

**Comment by rasendubi** [comment]
LGTM

@forGGe?

**Comment by forGGe** [comment]
+1

**Pull request merged**
