### PR TITLE
KAA-1288: ESP8266 C SDK CMakeLists: uses wrong path

### PR DESCRIPTION
**Pull request by tkhalymon**
Fixed KAA-1288

### CODE REVIEW

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by tkhalymon** [comment]
It's already in review, Maxim Olender or Alexey Shmalko can verify

**Comment by rasendubi** [comment]
@tkhalymon that's a bot ;)

@kaa-leeroy add to whitelist

**Comment by vadimol** [comment]
Looks good for me, however I do not see any references to this examples in ESP8266 guide. Can we drop it at all?

**Comment by forGGe** [comment]
@vadimol  Let's keep it. But we need to provide references in the guide to this attachments.

**Comment by rasendubi** [comment]
This attachment is expected to be an extract from some guide.

@vadimol could you please open a ticket to automate the building of all attachments we have? (That's kind of test our examples in the documentation still work.)

**Pull request merged**
