### PR TITLE
KAA-1280: Unable to generate code for deserialisation arrays of double

### PR DESCRIPTION
**Pull request by hamsternik**

### CODE REVIEW

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by abohomol** [comment]
@rasendubi, please, rerun those checks since proposed code doesn't affect C++ SDK (Travis detected failures in *.cpp files)

**Comment by abohomol** [comment]
@dyosick Please, review

**Comment by rasendubi** [comment]
@kaa-leeroy add to whitelist

**Comment by ghost** [comment]
LGTM

**Pull request merged**
