### PR TITLE
KAA-1272 Search for avrogencpp in $PATH

### PR DESCRIPTION
**Pull request by rasendubi**
cc @forGGe

### CODE REVIEW

**Comment by forGGe** [comment]
+

**Comment by rasendubi** [comment]
Jenkins has failed because avrogencpp is not in $PATH.

/cc @Oldnickus

**Comment by rasendubi** [comment]
@kaa-leeroy retest this please

**Comment by Oldnickus** [comment]
@kaa-leeroy retest this please

**Comment by rasendubi** [comment]
@kaa-leeroy retest this please

**Comment by vadimol** [comment]
+

**Pull request merged**
