### PR TITLE
JEK-11: [Doc design] Redesign table of contents.

### PR DESCRIPTION
**Pull request by Faradey27**

### CODE REVIEW

**Comment by Oldnickus** [comment]
@kaa-leeroy Retest this please

**Comment by Faradey27** [comment]
@rasendubi can you restart tests?

**Comment by vadimol** [comment]
@kaa-leeroy retest this please

**Comment by rasendubi** [comment]
Restarted Travis job.

**Comment by rasendubi** [comment]
@kaa-leeroy retest this please

**Review by Slash32 — APPROVED** [review]

**Review by vadimol — APPROVED** [review]
Jenkins and Travis fails are not related.

**Pull request merged**
