### PR TITLE
KAA-1440: [Objective-C SDK] Add noConnectivityRetryPeriod property to FailoverStrategy protocol.

### PR DESCRIPTION
**Pull request by am1kk**
http://jira.kaaproject.org/browse/KAA-1440

### CODE REVIEW

**Comment by am1kk** [comment]
@abohomol Review please.

**Comment by abohomol** [comment]
LGTM

**Comment by rasendubi** [comment]
@kaa-leeroy retest this please

**Comment by rasendubi** [comment]
@kaa-leeroy retest this please

**Pull request merged**
