### PR TITLE
KAA-1077: Add patch for avro for rpi cross-compilation

### PR DESCRIPTION
**Pull request by ohamov**

### CODE REVIEW

**Comment by forGGe** [comment]
commit lacks issue number, please fix

**Comment by rasendubi** [comment]
Rename file to `avro-cpp.patch`. Or better `avro-cpp-disable-tests.patch`.

**Comment by ohamov** [comment]
re-opened https://github.com/kaaproject/kaa/pull/692

**Comment by rasendubi** [comment]
Why closing/reopening?

**Pull request closed without merging**
