### PR TITLE
correct type error from messageQueueLingth to messageQueueLength in s…

### PR DESCRIPTION
**Pull request by DeepLn**
…erver/common/server-shared/src/main/java/org/kaaproject/kaa/server/thrift/NeighborConnection.java

### CODE REVIEW

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by DeepLn** [comment]
correct type error

**Comment by rasendubi** [comment]
@kaa-leeroy test this please

**Comment by rasendubi** [comment]
Thank you!

**Pull request merged**
