### PR TITLE
KAA-1638: [Objective-C] Incorrect generation of "description" method.

### PR DESCRIPTION
**Pull request by am1kk**
http://jira.kaaproject.org/browse/KAA-1638

### CODE REVIEW

**Comment by am1kk** [comment]
@abohomol review please.

**Review by abohomol — APPROVED** [review]
LGTM

**Comment by vadimol** [comment]
Jenkins fails due to http://jira.kaaproject.org/browse/KAA-1640

**Comment by vadimol** [comment]
Mistakenly closed this PR.

**Review by vadimol — APPROVED** [review]

**Pull request merged**
