### PR TITLE
KAA-1293: Move email and user existence check methods from Web UI to …

### PR DESCRIPTION
**Pull request by Pyshankov**
…REST API method

### CODE REVIEW

**Comment by Pyshankov** [comment]
@kaa-leeroy re-test this please.

**Comment by vadimol** [comment]
@kaa-leeroy re-test this please.

**Comment by Pyshankov** [comment]
@Oldnickus, please, clean up tmp folder and re-test this please.

**Comment by Oldnickus** [comment]
@kaa-leeroy retest this please

**Comment by Pyshankov** [comment]
@kaa-leeroy re-test this please

**Comment by vadimol** [comment]
@kaa-leeroy retest this please

**Comment by Pyshankov** [comment]
@kaa-leeroy retest this please

**Comment by Pyshankov** [comment]
@Oldnickus, please, clean up tmp folder and re-test this please.

**Pull request merged**
