### PR TITLE
KAA-1574: Change KAA SDK path in cmake arguments

### PR DESCRIPTION
**Pull request by yverzun**

### CODE REVIEW

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by rasendubi** [comment]
@kaa-leeroy add to whitelist

**Review by rasendubi — APPROVED** [review]
LGTM. Should this be backported to 0.10.1?

**Review by vadimol — APPROVED** [review]
LGTM.
@rasendubi , yes, it should be backported to 0.10.1

**Comment by rasendubi** [comment]
@yverzun, please, backport

**Pull request merged**
