### PR TITLE
KAA-1302: User management - reviewed.

### PR DESCRIPTION
**Pull request by hunch7**
Done as per https://github.com/kaaproject/kaa/pull/1360

### CODE REVIEW

**Comment by Oldnickus** [comment]
@kaa-leeroy retest this please

**Comment by Oldnickus** [comment]
@kaa-leeroy retest this please

**Comment by Oldnickus** [comment]
@kaa-leeroy test this fully please

**Comment by Oldnickus** [comment]
@kaa-leeroy test this please

**Comment by Oldnickus** [comment]
@kaa-leeroy test this fully please

**Comment by Oldnickus** [comment]
retest this please

**Comment by Oldnickus** [comment]
retest this please

**Comment by Oldnickus** [comment]
retest this please

**Comment by vadimol** [comment]
Jenkins fail is not related.

**Review by vadimol — APPROVED** [review]

**Pull request merged**
