### PR TITLE
KAA-1634: Sections hierarchy changed in the sidebar, links fixed acco…

### PR DESCRIPTION
**Pull request by hunch7**
…rdingly.

### CODE REVIEW

**Review by Polinaa — APPROVED** [review]

**Comment by vadimol** [comment]
Please, resolve merge conflicts and update the PR

**Review by vadimol — CHANGES_REQUESTED** [review]
Please, resolve merge conflicts and update the PR

**Comment by hunch7** [comment]
Merge conflict resolved in this PR: https://github.com/kaaproject/kaa/pull/1494

**Comment by hunch7** [comment]
Merge conflict resolved in this PR: #1494

**Pull request closed without merging**
