### PR TITLE
Docker container

### PR DESCRIPTION
**Pull request by axuan25**
This pull request differs greatly from the original docker container found on the Kaa repository. As discussed over email and skype, here is the initial pull request for my own Kaa container.

JIRA: http://jira.kaaproject.org/browse/KAA-1237

I look forward to your input!

### CODE REVIEW

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by rasendubi** [comment]
Hi, Chris! Could you please rebase your branch on the `develop` leaving only your commit and open a pull request against `develop` (not `develop-1.0.0`). (better commit wording would be also good)

**Comment by rasendubi** [comment]
If you're interested, there is more info on our git flow [here](http://docs.kaaproject.org/display/KAA/Git+Flow).

**Comment by axuan25** [comment]
@rasendubi I can rebase from develop, but my understanding was that this would be included in 1.x? Apologies for the commit wording: being a pretty "large" PR, I'm not too sure how to describe this change.

**Comment by rasendubi** [comment]
I would like to get this included earlier, as I don't see a reason to wait for 1.x for this.

As for naming, `KAA-1237 Docker container` is good enough.

**Pull request closed without merging**
