### PR TITLE
KAA-677 Compilation guide for C++ SDK (Intel Edison) on Linux platform

### PR DESCRIPTION
**Pull request by vadimol**
Fixed compilation guide for C++ SDK for Intel Edison

### CODE REVIEW

**Comment by Dubland** [comment]
Should be checked.
Overall, LGTM

**Comment by vadimol** [comment]
@kaa-leeroy test this please

**Comment by vadimol** [comment]
@kaa-leeroy retest this please

**Comment by vadimol** [comment]
Checked on Intel Edison. Merging PR.

**Pull request merged**
