### PR TITLE
KAA-1114 C SDK porting guide

### PR DESCRIPTION
**Pull request by rasendubi**
/cc @vadimol @sparadiuk

### CODE REVIEW

**Comment by vadimol** [comment]
@kaa-leeroy retest this please

**Review by vadimol — APPROVED** [review]
LGTM

**Review by forGGe — APPROVED** [review]
+1

**Comment by vadimol** [comment]
@kaa-leeroy retest this please

**Comment by vadimol** [comment]
Jenkins fails, see http://jira.kaaproject.org/browse/KAA-1432 for details. This patch does not change the code. It can be merged.

**Pull request merged**
