### PR TITLE
KAA-1208: Same response comes again from Server

### PR DESCRIPTION
**Pull request by ashvayka**
This is both server and client side issue. But due to absence of the server side logs and low priority of this issue in context of new extension redesign, I have fixed this only on the client side.

### CODE REVIEW

**Comment by ikulikov** [comment]
@kaa-leeroy retest this please

**Comment by ikulikov** [comment]
@kaa-leeroy retest this please

**Comment by ikulikov** [comment]
@kaa-leeroy retest this please

**Comment by Oldnickus** [comment]
@kaa-leeroy retest this please

**Pull request merged**
