### PR TITLE
KAA-1157 - Add blockquote.note class

### PR DESCRIPTION
**Pull request by dr3amf4ll**

### CODE REVIEW

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by balldir** [comment]
LGTM

**Comment by Oldnickus** [comment]
add to whitelist

**Comment by akokhanovskyi** [comment]
What's the ticket number here?

**Comment by balldir** [comment]
I think it's KAA-1157

**Review by balldir — APPROVED** [review]

**Review by balldir — APPROVED** [review]

**Pull request merged**
