### PR TITLE
KAA-1444: Fix method editUser() in AdminUI

### PR DESCRIPTION
**Pull request by v-chyzhevskyi**
During creation of tenant administrator on behalf of KAA_ADMIN, calling method getUsers()(only for TENANT_ADMIN) from method editUser() in AdminUI.

### CODE REVIEW

**Comment by chv348** [comment]
@kaa-leeroy retest this

**Comment by v-chyzhevskyi** [comment]
@kaa-leeroy retest this

**Comment by vadimol** [comment]
@kaa-leeroy retest this please

**Comment by Oldnickus** [comment]
@kaa-leeroy retest this please

**Pull request merged**
