### PR TITLE
KAA-1237 Docker container

### PR DESCRIPTION
**Pull request by axuan25**
This refers to KAA-1237. Hopefully, this PR does the job!

Looking forward to your input.

Best,
Christopher B.

### CODE REVIEW

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by rasendubi** [comment]
The Travis build has failed. Seems that you've added the files without the license header. Could you please either add it to the files or add files to the exclude filters in `pom.xml`?

You can check that locally with `mvn apache-rat:check`.

**Comment by kaa-leeroy** [comment]
retest this please

**Comment by axuan25** [comment]
I will get the license headers in there asap. Apologies for the late replies, work's been busy! Also bracing for typhoon Nepartak here...

**Comment by akokhanovskyi** [comment]
@axuan25 appreciate the contribution! We'll do the code review once the automatic checks complete.

Stay safe there!

**Comment by akokhanovskyi** [comment]
@Deepnekroz please watch this

**Comment by axuan25** [comment]
Haven't forgotten about this! Had to release a new version of our own application here. Will be getting back to this PR in the following week.

Best

**Comment by axuan25** [comment]
The license headers have been added!
Docker 1.12 brings about quite a few changes, and I have a bunch of stuff I want to change about this image. However, it's working fine on our end here. I will be getting back to this project in October when I get actual free time. In the meanwhile, let me know if you need any assistance with anything else.

Regards,

**Comment by ikulikov** [comment]
@axuan25 This PR changes were incorporated and merged in scope of PR#1113.

**Pull request closed without merging**
