### PR TITLE
KAA-1324: Broken links on Using-Kaa-endpoint-SDKs/C page

### PR DESCRIPTION
**Pull request by vasner**
Fix broken links on Using-Kaa-endpoint-SDKs/C page
Reviews: @forGGe and @rasendubi

### CODE REVIEW

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by rasendubi** [comment]
@kaa-leeroy add to whitelist

**Comment by forGGe** [comment]
Looks good

**Comment by balldir** [comment]
LGTM

**Comment by vadimol** [comment]
+

**Pull request merged**
