### PR TITLE
KAA-1255: Improved cassandra log appender.

### PR DESCRIPTION
**Pull request by Acarus**
- Handle large batches (greater than batch_size_fail_threshold_in_kb from cassandra.yaml).
- One log appender is able to manage several tables (log types) using activation condition.

### CODE REVIEW

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by akokhanovskyi** [comment]
@Acarus Please open a JIRA ticket with the changes description and follow the standard PR procedure.

**Comment by Oldnickus** [comment]
@kaa-leeroy add to whitelist

**Comment by akokhanovskyi** [comment]
@Acarus @ashvayka Looks like this PR needs an update.

**Pull request closed without merging**
