### PR TITLE
KAA-1024: Set default server log level to WARN

### PR DESCRIPTION
**Pull request by krupet**

### CODE REVIEW

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by rasendubi** [comment]
@kaa-leeroy add to whitelist

**Comment by ashvayka** [comment]
Usually, server log level should be set to INFO, why we are setting to WARN?

**Comment by akokhanovskyi** [comment]
@krupet @ashvayka Can we drop this PR? I think we agreed that the appropriate way to solve the issue at hand is by reviewing logging levels in general.

**Comment by rasendubi** [comment]
Closing this. If still needed, feel free to reopen.

**Pull request closed without merging**
