### PR TITLE
KAA-1348 Fix unknown CMake command cmake_parse_arguments

### PR DESCRIPTION
**Pull request by rasendubi**
This also includes fix for  KAA-1349, as it was needed to reproduce the issue.

### CODE REVIEW

**Comment by rasendubi** [comment]
@rasendubi remember to retrigger #990 after merge of this.

**Comment by vadimol** [comment]
+

**Comment by rasendubi** [comment]
Changes from #990 are needed to pass travis/jenkins.

**Comment by forGGe** [comment]
looks good

**Pull request merged**
