### PR TITLE
KAA-1157 gh-pages-stub update

### PR DESCRIPTION
**Pull request by balldir**

### CODE REVIEW

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by balldir** [comment]
This patch is tightly coupled with https://github.com/kaaproject/kaa/pull/794 . Unfortunately, this patches are for different branches and can't be added to the single pull request.

**Comment by Oldnickus** [comment]
@kaa-leeroy 
add to whitelist

**Pull request merged**
