### PR TITLE
KAA-1594: error after attaching endpoint to user

### PR DESCRIPTION
**Pull request by xiaoyaoweizi**
I try to fix the bug (KAA-1594   error after attaching endpoint to user) . The code that I fixed run successfully. But I do not know that such a change will cause other problem.

### CODE REVIEW

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by rasendubi** [comment]
@kaa-leeroy test this please

**Comment by rasendubi** [comment]
@kaa-leeroy test this please

**Comment by vtkhir** [comment]
@xiaoyaoweizi, I'm unable to reproduce the described issue. 
See [my comment](http://jira.kaaproject.org/browse/KAA-1594?focusedCommentId=19651&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-19651) in related jira bug. Can you please provide more detailed steps to reproduce  in the [KAA-1594](http://jira.kaaproject.org/browse/KAA-1594)?
Thanks

**Comment by vtkhir** [comment]
@xiaoyaoweizi, I have to reject the PR. See [my jira comment](http://jira.kaaproject.org/browse/KAA-1594?focusedCommentId=20052&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-20052) for details. Let me know if you have any questions.

**Pull request closed without merging**
