### PR TITLE
KAA-1630:  GPIOdemo C client do not send event response

### PR DESCRIPTION
**Pull request by AlexShev76**

### CODE REVIEW

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by Slash32** [comment]
@kaa-leeroy add to whitelist

**Review by Slash32 — APPROVED** [review]
/cc @rasendubi this needs to be merged to master as well.

**Review by vadimol — DISMISSED** [review]
This is a workaround. 
The Jira ticket has been created http://jira.kaaproject.org/browse/KAA-1630. 
The bug will be investigated and fixed in the scope of this ticket.

@AlexShev76 , please open the PR against master branch

**Comment by rasendubi** [comment]
@AlexShev76 could you please elaborate on why the change is needed? (I have nothing against it, just trying to understand.)

**Comment by Slash32** [comment]
@rasendubi it looks like the SDK and demo modules are somehow built with different headers that provide different size to size_t. Thus, the 64-bit value upon function call is passed as 64-bit and read out within the function as 32-bit dropping the lower 32-bit part, etc.

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Comment by rasendubi** [comment]
@Slash32 how casting values before calling the function helps? If the function implementation and invocation use different types, that's UB. (Casting values before invocation won't help.)

**Review by rasendubi — CHANGES_REQUESTED** [review]
Now I don't trust the patch and would like this not merged until I get a good explanation of how this works.

**Comment by vadimol** [comment]
Closing this PR until the proper fix will be provided.

**Pull request closed without merging**
