### PR TITLE
Kaa 1282: Review all C code samples in new Documentation

### PR DESCRIPTION
**Pull request by mlysenko**

### CODE REVIEW

**Comment by rasendubi** [comment]
@mlysenko please, resolve merge conflict

**Comment by mlysenko** [comment]
@rasendubi resolved

**Comment by vadimol** [comment]
Overall, looks good for me. However, @mlysenko didn't you forget to update code in "You first Kaa Application"?

**Comment by mlysenko** [comment]
@vadimol, yes I did. Fixed "You first Kaa Application".

**Comment by vadimol** [comment]
@kaa-leeroy retest this please

**Comment by vadimol** [comment]
LGTM

**Pull request merged**
