### PR TITLE
EVA-105: DO NOT MERGE

### PR DESCRIPTION
**Pull request by odovhai**
Just for testing PR https://github.com/kaaproject/kaa/pull/1361

### CODE REVIEW

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by odovhai** [comment]
@kaa-leeroy test this please

**Comment by Slash32** [comment]
@kaa-leeroy add to whitelist

**Comment by odovhai** [comment]
@kaa-leeroy test this please

**Comment by odovhai** [comment]
@kaa-leeroy test this please

**Pull request closed without merging**
